### ISSUE TITLE
What is the state of this project?

### ISSUE THREAD

**Issue by fiatjaf** [dreftymac/stackoverflow.questions.998832#1]
As far as I can understand (from reading random stuff in your repos), I have the same goal you have (and I've been having it for years now), that of enabling normal people to write structured data in an easy way, for various purposes. That's why I found your StackOverflow question yesterday (after various unfruitful searches over the last months).

So, if you allow me to ask things after this brief introduction, my question is: what exactly are you trying to solve? Have you reached some solution? Have you given up? Do you have any project, idea, some nice thing you're trying to do with all this?

For myself, there's a thing I'm trying to implement: a multipurpose related and structured data management tool that people can use instead of Excel, to add data in an organized way, I've called it [youfle](https://github.com/fiatjaf/youfle) and it uses raw YAML text, nothing fancy (there's [a working demo here](http://fiatjaf.alhur.es/youfle/)) (I may think the ideal structured data editor would be a simple textarea with YAML syntax highlighting and syntax enforcement, but I don't know exactly how would be the "enforcement" part).

**Comment by dreftymac** [comment]
Greetings fiatjaf,

This repository we are in right now is just for tracking the StackOverflow (SO) post.

**//What is the state of this project?//**

There is a specification that I have been working on for the actual project itself, but progress has been slow as I have been determining interest.

**//what exactly are you trying to solve?//**

Based on what you have posted here, it is apparent we have a very similar underlying idea.

**//Have you reached some solution? Have you given up? Do you have any project, idea, some nice thing you're trying to do with all this?//**

Hmm .. that's a good question. Part of what I am doing is evaluating what prevents this approach from already being a well-known thing. Another part is evaluating interest. You seem to have an understanding of some of the underlying goals already. 

**//I may think the ideal structured data editor would be a simple textarea with YAML syntax highlighting and syntax enforcement, but I don't know exactly how would be the "enforcement" part//**

The specification I've been working on covers some of these details, but there is not a repository for the specification yet.

The youfle repository and demo looks interesting, thanks for the link. 

**//I'm trying to implement: a multipurpose related and structured data management tool that people can use instead of Excel//**

Yes! This is very important.

One issue with this ... there are a lot of "spreadsheet" solutions out there and _most people who use spreadsheets think in terms of spreadsheets_ for structured data. 

As you obviously realize, spreadsheets are not enough, but most non-programmers (people who do not use github or do not even know what github is) reach their limit of understanding if you talk about anything more complex than a spreadsheet (such as YAML or JSON).

**Comment by fiatjaf** [comment]
I'm currently trying a crude approach (YAML textarea with CodeMirror syntax highlighing) for people to edit their tiny profiles on a website. It was tested now with somewhat 15 non-tech people. Everybody managed to edit simple text fields, maybe 6 or 7 of them tried to edit array fields, and no one succeeded (they have failed to match the indentation level and the array got converted into a string).

**Comment by fiatjaf** [comment]
The other (much more serious) use for a general structured data application is the replacement of the millions of CRUD software out there. Trello is an example of success in replacing every "organize something" CRUD apps with predefined data types (notes, columns, reminders, forum threads, calendars, tasks, assignments, roles etc.) with an app every user can use in their own way while maintaining some structure.

[Youfle](https://github.com/fiatjaf/youfle) (as you noticed, an unfinished and temporarily abandoned work) is an attempt to do this for _really_ structured data. A way people (and companies, mainly) can (loosely) define their own data types and relations between them, then organize their data following these defined data types, and also make computations with that data (I was thinking simple things: filtering data by keys, counting and summing properties matching this filter, generating HTML from templates + the results of these computations).

Every time I see lots of people employed writing -- and, at the other side, lots of people paying for -- CRUD apps, every one of them so equal to each other, with only table and column names differing, I die a little.

**Comment by dreftymac** [comment]
**// I see lots of people employed writing -- and, at the other side, lots of people paying for -- CRUD apps, every one of them so equal to each other, with only table and column names differing, //**

Well, yes. There is a lot of investment in these areas, and justifiably so. Everyone desires to find a niche in the market. We have to take note of "disruptive" technologies, and the desire to keep things simple, clean, and flexible.
